POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZ1cmlvbG92ZXI3IiwiaWQiOiI2M2ZhNmU3MDA3Yzk1N2VmYjViMGU2ZGYiLCJpYXQiOjE2Nzc1NDQ0NzB9.4r4BcBNVaRJlzgxasGyv6nDH5zxxbHBva1ACvvVUPy8

{
    "title": "Tony is cool!",
    "author": "billy stewart",
    "url": "tonyiscool.net",
    "likes": 70
}