DELETE http://localhost:3003/api/blogs/63fbb40ba00324e7127a4bbb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZ1cmlvbG92ZXI3IiwiaWQiOiI2M2ZhNmU3MDA3Yzk1N2VmYjViMGU2ZGYiLCJpYXQiOjE2Nzc2MzA2NjV9.ZBHsqCLYSAMIM0jJqVNSuB7boWcW-mkqM4-OIlF-fb0